# Workflow name
name: dynamic-workflow

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
    inputs:
	  index_document:
	    default: 'index.html'
	  error_document:
        default: 'error.html'	  
env:
  BUCKET_NAME:website-artifacts		
  
jobs: # Jobs defined in the workflow
  create-stack:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
   
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
        aws-region: us-east-1

    - name: Create CloudFormation Stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: uda-artifact
        template: uda_artifact.yml
		
    - name: Upload files into S3
      run: |
	     aws s3 cp ./website/${{github.event.input.index_document}} s3://${{env.BUCKET_NAME}}
		 aws s3 cp ./website/${{github.event.input.error_document}} s3://${{env.BUCKET_NAME}}
		 
    - name: Show S3 bucket URL
      run: |
	     aws cloudformation describe-stack --stack-name uda-artifcat --query 'Stacks[0].Outputs[?OutputKey=='ArtifactBucketWebsiteURL'].OutputValue' --output text
		 	 
		 
        
        